### ISSUE TITLE
Gremlin Compile Errors

### ISSUE THREAD

**Issue by komeara1** [slaeryan/MIDNIGHTTRAIN#1]
As a non-devevloper by trade I'm getting this errors. 

C:\Users\admin\Desktop\MIDNIGHTTRAIN\Gremlin>compile64.bat
Gremlin.cpp
dllmain.cpp
Generating Code...
   Creating library ..\\Bin\\gremlin_x64.lib and object ..\\Bin\\gremlin_x64.exp
Gremlin.obj : error LNK2019: unresolved external symbol __imp_OpenProcessToken referenced in function "int __cdecl steal_token(unsigned long)" (?steal_token@@YAHK@Z)
Gremlin.obj : error LNK2019: unresolved external symbol __imp_OpenThreadToken referenced in function "int __cdecl enable_privilege(char const *)" (?enable_privilege@@YAHPEBD@Z)
Gremlin.obj : error LNK2019: unresolved external symbol __imp_AdjustTokenPrivileges referenced in function "int __cdecl enable_privilege(char const *)" (?enable_privilege@@YAHPEBD@Z)
Gremlin.obj : error LNK2019: unresolved external symbol __imp_GetTokenInformation referenced in function "int __cdecl verify_priv(void *,char const *)" (?verify_priv@@YAHPEAXPEBD@Z)
Gremlin.obj : error LNK2019: unresolved external symbol __imp_ImpersonateLoggedOnUser referenced in function "int __cdecl steal_token(unsigned long)" (?steal_token@@YAHK@Z)
Gremlin.obj : error LNK2019: unresolved external symbol __imp_RevertToSelf referenced in function "void __cdecl go(void)" (?go@@YAXXZ)
Gremlin.obj : error LNK2019: unresolved external symbol __imp_LookupPrivilegeValueA referenced in function "int __cdecl verify_priv(void *,char const *)" (?verify_priv@@YAHPEAXPEBD@Z)
..\\Bin\\gremlin_x64.dll : fatal error LNK1120: 7 unresolved externals

Am I missing a #include for the TokenSteal.h? Or something else.

**Comment by slaeryan** [comment]
Hey!
I think that is a linker issue, if you include the following line exactly at the top of the header file named TokenSteal.h (say line 4):
#pragma comment(lib, “Advapi32.lib”)

This should fix it but I’m keeping the issue open for now.
Lemme know if you need additional help with something :)

**Comment by komeara1** [comment]
That was it. Thank you!
